---
title: "Mixed Effects Project Revisited - Formulas"
date: "11/26/2020"
output: html_document
self_contained: yes
---

# Intro
The goal is to find the effect of a change $\Delta$ in random-effect $Z_{p}$ (*QB, Team, Opponent*) have on passing efficiency $(EPA_{pass,i})$ while controlling for the other random effects. I made these formulas aimed to estimate coefficients $\theta_{p}$, and explain marginal effects of any random effect on $(EPA_{pass,i})$ dependent on the remaining random-effects. 

$X_{p}$ is any fixed-effect(s); their/its coefficient(s) $\beta_{p}$ will be estimated using OLS. $\theta_{p}$ will be estimated via the factorization of the list of the intercepts (multilevel) of each $p$ random effect.

**Effect of $\Delta$ Quarterback Dependent on Team**
$$
\large {EPA}_{pass,i} = \beta_{p} X_{pi} + \theta_{1}{QB}_{i} + \theta_{2}{Team}_{i}+ \theta_{3}{Team}_{i}{QB}_{ij} +\in_{i}
$$  

$$
\large 
\frac{{EPA}_{pass,i}}{\Delta {QB}} = \theta_{1} + \theta_{3}{Team}_{i} 
$$  
**Effect of Team Dependent on QB**
$$
\large 
\frac{{EPA}_{pass,i}}{\Delta Team} = \theta_{2} + \theta_{3}{QB}_{i}  
$$  
**QB dependent on Team and Opponent**
$$ 
\large
{EPA}_{pass,i}= \theta_{1}{QB}_{i} + \theta_{2}{Team}_{i} + \theta_{3}{Team}_{i}QB_{i} + \theta_{4}{Opponent}_{i}+ \theta_{5}{Opponent}_{i} {QB}_{i} +\in_{i}
$$

$$
\large 
\frac{{EPA}_{pass,i}}{\Delta {QB}} = \theta_{1} + \theta_{3}{Team}_{j}+ \theta_{5}{Opponent}_{j} 
$$  


**Let's get funny**

$$
\large
{EPA}_{pass,i} = \beta_{p,i}X_{p,i} +\theta_{1}{QB}_{i} + \theta_{2}{Team}_{i} + \theta_{3}{Team}_{i}{QB}_{i} + \theta_{4}{Opponent}_{i}+ \theta_{5}{Opponent}_{i}QB_{i} + \theta_{6}Opponent_{i}Team_{i} +\in_{i}
$$

With this formula, I should be able to estimate the coefficients $\theta_{1},\theta_{3},\theta_{4}$

$$
\large 
\frac{{EPA}_{pass,i}}{\Delta {QB}} = \theta_{1} + \theta_{3}{Team}_{i}+ \theta_{5}{Opponent}_{i} 
$$ 

$$
\large 
\frac{{EPA}_{pass,i}}{\Delta {Team}} = \theta_{2} + \theta_{3}{QB}_{i}+ \theta_{6}{Opponent}_{i} 
$$ 

$$
\large 
\frac{{EPA}_{pass,i}}{\Delta {Opponent}} = \theta_{4} + \theta_{5}{QB}_{i}+ \theta_{6}{Team}_{i} 
$$ 

The coefficients $\theta_{1},\theta_{3},\theta_{4}$ should be able to tell us the impact that $QB$, $Team$, and $Opponent$ have on Pasing Efficiency.


